name: auto_tag
on:
  push:
    branches:
      - main
      - develop
      - qa
jobs:
  tag_repo:
    name: Get githubs workflow head SHA and generate tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a tag based on the workflow SHA
        run: |
          git tag ${{github.run_id}}
          git push origin ${{github.run_id}}
